name: xSpawn
main: dev.drygo.XSpawn.XSpawn
version: 0.0.01
api-version: 1.20
authors:
  - Drygo
commands:
  xspawn:
    aliases:
      - xsp
    description: "xSpawn plugin command."
permissions:
  xspawn.admin:
    default: false
    children:
      xspawn.command.set:
        default: false
      xspawn.command.tp:
        default: false
      xspawn.command.del:
        default: false
      xspawn.command.reload:
        default: false
      xspawn.command.help:
        default: false
      xspawn.command.info:
        default: false