name: xSpawn
main: dev.drygo.XSpawn.XSpawn
version: 1.0
api-version: 1.20
authors:
  - Drygo
soft-depend:
  - xTeams
commands:
  xspawn:
    aliases:
      - xsp
      - xs
    description: "xSpawn plugin command."
permissions:
  xspawn.admin:
    default: false
    children:
      xspawn.command.set:
        default: false
      xspawn.command.tp:
        default: false
      xspawn.command.del:
        default: false
      xspawn.command.reload:
        default: false
      xspawn.command.help:
        default: false
      xspawn.command.info:
        default: false